# Generated by Django 5.0.4 on 2024-07-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('book_number', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.TextField(null=True)),
                ('auther', models.TextField(null=True)),
                ('publisher', models.TextField(null=True)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
