# Generated by Django 5.0.4 on 2024-07-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='auther',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.TextField(default='김승주', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.IntegerField(default='2024'),
        ),
    ]
