# Generated by Django 5.0.4 on 2024-07-11 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0002_remove_book_auther_book_author_book_publication_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
